export type DemoContact = {
  id: string;
  initials: string;
  name: string;
  title?: string;
  tags: string[];
  location: string;
  lastContact: string;
  daysAgo: number;
  status?: "overdue" | "today" | "upcoming";
  nextMeetDate?: string;
};

export const demoContacts: DemoContact[] = [
  {
    id: "4",
    initials: "EN",
    name: "Edward Norton",
    title: "Class 5 Films",
    tags: ["Friend", "Work"],
    location: "New York",
    lastContact: "Jan 10",
    daysAgo: 3,
    nextMeetDate: "2026-02-05",
  },
  {
    id: "5",
    initials: "DB",
    name: "Dan Brown",
    title: "Author",
    tags: ["New"],
    location: "New York",
    lastContact: "Jan 13",
    daysAgo: 0,
  },
  {
    id: "1",
    initials: "SC",
    name: "Sarah Chen",
    title: "Stripe",
    tags: ["Friend", "Work"],
    location: "San Francisco",
    lastContact: "Dec 1",
    daysAgo: 43,
    status: "overdue",
    nextMeetDate: "2026-01-18",
  },
  {
    id: "6",
    initials: "AL",
    name: "Ava Lin",
    title: "Figma",
    tags: ["Work"],
    location: "San Francisco",
    lastContact: "Jan 5",
    daysAgo: 8,
  },
  {
    id: "7",
    initials: "RM",
    name: "Ravi Mehta",
    title: "Anthropic",
    tags: ["Work", "Friend"],
    location: "New York",
    lastContact: "Dec 18",
    daysAgo: 26,
    nextMeetDate: "2026-02-12",
  },
  {
    id: "8",
    initials: "KC",
    name: "Kara Cole",
    tags: ["Family"],
    location: "Austin",
    lastContact: "Jan 2",
    daysAgo: 11,
  },
  {
    id: "9",
    initials: "JL",
    name: "Jonas Lee",
    title: "Tesla",
    tags: ["Friend"],
    location: "Austin",
    lastContact: "Dec 22",
    daysAgo: 22,
    nextMeetDate: "2026-01-20",
  },
  {
    id: "10",
    initials: "MP",
    name: "Maya Patel",
    title: "Shopify",
    tags: ["Work"],
    location: "Toronto",
    lastContact: "Jan 11",
    daysAgo: 2,
  },
  {
    id: "11",
    initials: "OB",
    name: "Owen Brooks",
    title: "York University",
    tags: ["Friend"],
    location: "Toronto",
    lastContact: "Nov 29",
    daysAgo: 45,
    status: "overdue",
    nextMeetDate: "2026-01-10",
  },
  {
    id: "12",
    initials: "HG",
    name: "Hana Garcia",
    tags: ["Friend"],
    location: "Miami",
    lastContact: "Dec 30",
    daysAgo: 14,
  },
  {
    id: "13",
    initials: "LS",
    name: "Liam Stone",
    title: "Meta",
    tags: ["Work"],
    location: "Miami",
    lastContact: "Jan 4",
    daysAgo: 9,
    nextMeetDate: "2026-03-01",
  },
  {
    id: "14",
    initials: "AP",
    name: "Ana Park",
    tags: ["Family"],
    location: "San Francisco",
    lastContact: "Dec 12",
    daysAgo: 32,
    status: "overdue",
    nextMeetDate: "2026-01-08",
  },
  {
    id: "15",
    initials: "CB",
    name: "Chris Bell",
    title: "Goldman Sachs",
    tags: ["New"],
    location: "New York",
    lastContact: "Jan 9",
    daysAgo: 4,
  },
  {
    id: "16",
    initials: "NT",
    name: "Nina Torres",
    tags: ["Friend"],
    location: "Austin",
    lastContact: "Dec 26",
    daysAgo: 18,
  },
  {
    id: "17",
    initials: "GB",
    name: "Gabe Rossi",
    title: "Deloitte",
    tags: ["Work"],
    location: "Toronto",
    lastContact: "Jan 6",
    daysAgo: 7,
  },
  {
    id: "18",
    initials: "SF",
    name: "Sophie Fox",
    tags: ["New"],
    location: "Miami",
    lastContact: "Dec 15",
    daysAgo: 29,
  },
  {
    id: "19",
    initials: "ID",
    name: "Ivan Diaz",
    title: "Airbnb",
    tags: ["Friend"],
    location: "San Francisco",
    lastContact: "Jan 1",
    daysAgo: 12,
    nextMeetDate: "2026-01-28",
  },
  {
    id: "20",
    initials: "VT",
    name: "Vera Tan",
    title: "McKinsey",
    tags: ["Work"],
    location: "New York",
    lastContact: "Dec 8",
    daysAgo: 36,
    status: "overdue",
    nextMeetDate: "2026-01-14",
  },
];
